### ISSUE TITLE
Unable to enter text in eq-author 'create' page

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-author#101]
### Expected behaviour
Must allow entering text.

### Actual behaviour
Does not allow to enter text.

### Steps to reproduce the behaviour
Launch eq-author
click [Create Survey]
Try entering any text in 'Title' field

#### Browser
Chrome

**Comment by samiwel** [comment]
@yoganandkunche Are you happy to close this defect now?

**Comment by yoganandkunche** [comment]
Works as expected.

**Comment by samiwel** [comment]
As discussed will close this with the PR 👍
