### ISSUE TITLE
Checkbox values being lost upon adding/removing options

### ISSUE THREAD

**Issue by samiwel** [ONSdigital/eq-author#191]
### Expected behaviour
The values entered should be persisted when new options are added and other options are deleted.

### Actual behaviour
The entered labels are being lost.

### Steps to reproduce the behaviour
Enter some values into the options of a Checkbox answer, add new options or remove some options.

### Technical information
Did some preliminary investigation and I believe it's down to the focus logic https://github.com/ONSdigital/eq-author/blob/master/src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js#L71

### Screenshot
![checkbox-values-being-lost](https://user-images.githubusercontent.com/4097796/30027134-808d5e10-9177-11e7-89ef-799fdbb1f825.gif)

**Comment by WickyNilliams** [comment]
Having tested this, I'm fairly certain we've fixed it via #188
