### ISSUE TITLE
Untitled section/pages titles different in navigation and move dialog

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-author#354]
### Expected behaviour

A page/section that has no user-defined title should be display with a consistent placeholder title throughout the UI.

### Actual behaviour

A section with no title displays "Section Title" in navigation.
A section with no title displays "Untitled Section" in move page dialog.

A page with no title displays "Page Title" in navigation.
A page with no title displays "Untitled Page" in move page dialog.

### Steps to reproduce the behaviour

1. Create any section or page with no title
2. Click the 'move' button
3. Labels in navigation and move dialogs are different

### Screenshot

<img width="1481" alt="screenshot 2018-05-08 10 03 41" src="https://user-images.githubusercontent.com/930398/39748379-d6d18e30-52a7-11e8-9038-8ce5ecd773fd.png">

**Comment by WickyNilliams** [comment]
I believe I took this format from the delete confirm modal:

![image](https://user-images.githubusercontent.com/1091390/40234977-9d6ed94e-5aa0-11e8-92c9-1b2dafaff76a.png)

**Comment by adammahmood** [comment]
Fixed by https://github.com/ONSdigital/eq-author/pull/425
