### ISSUE TITLE
Error message in console when creating a new Questionnaire

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-author#397]
### Expected behaviour

Creating a Questionnaire should happen without error

### Actual behaviour

When creating a Questionnaire an error is logged to the browser console:

<img width="834" alt="screenshot 2018-08-14 13 49 17" src="https://user-images.githubusercontent.com/930398/44092648-0273551e-9fc9-11e8-8a33-44576565bf76.png">

### Steps to reproduce the behaviour

- Login
- Create a Questionnaire
- Error is logged when app forwards you to the new Questionnaire

#### Browser

Chrome

#### Operating System

macOS

**Comment by adammahmood** [comment]
https://github.com/ONSdigital/eq-author/pull/409

**Comment by adammahmood** [comment]
Please close this issue once merged: https://github.com/ONSdigital/eq-author/issues/397
